#!/bin/sh
set -e

case "$1" in
remove | deconfigure)
    if [ -d /run/systemd/system ]; then
        systemctl disable --now host-guardian.service || true
    fi
    ;;
upgrade | failed-upgrade) ;;
*)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
